[project]
name = 'Galactic-Archaeology-Simulation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.collaboration-tools]
path = 'contracts/collaboration-tools.clar'
clarity_version = 2
epoch = 2.5

[contracts.galactic-discovery-nft]
path = 'contracts/galactic-discovery-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
